branch-defaults:
  master:
    environment: End-to-End-Pipeline-test
    group_suffix: null
global:
  application_name: End_to_End_Pipeline
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: ugupta-pm
  repository: null
  sc: git
  workspace_type: Application
